# Generated by Django 4.2.5 on 2023-10-24 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "picsart",
            "0007_remove_anonymoususerfunctionsusagecounter_ip_address_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="freeenhanceslimit",
            options={
                "verbose_name": "limit",
                "verbose_name_plural": "Free credits limit",
            },
        ),
    ]
