# Generated by Django 4.2.5 on 2023-10-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MainFaq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Title")),
                ("text", models.TextField(max_length=10000, verbose_name="Text")),
            ],
            options={
                "verbose_name": "faq",
                "verbose_name_plural": "Main FAQs",
                "db_table": "main_faqs",
            },
        ),
        migrations.CreateModel(
            name="PricingFaq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Title")),
                ("text", models.TextField(max_length=10000, verbose_name="Text")),
            ],
            options={
                "verbose_name": "faq",
                "verbose_name_plural": "Pricing FAQs",
                "db_table": "pricing_faqs",
            },
        ),
    ]
