# Generated by Django 4.2.5 on 2023-10-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "ACTIVE"),
                            ("IN PROCESSING", "IN PROCESSING"),
                            ("COMPLETED", "COMPLETED"),
                        ],
                        verbose_name="Request status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("text", models.TextField(verbose_name="Request text")),
            ],
            options={
                "verbose_name": "help request",
                "verbose_name_plural": "Help requests",
                "db_table": "help_requests",
            },
        ),
    ]
