# Generated by Django 4.2.5 on 2023-10-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_helprequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="helprequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("Functionality", "Functionality"),
                    ("Account", "Account"),
                    ("Pricing", "Pricing"),
                    ("Other", "Other"),
                ],
                default="Functionality",
                verbose_name="Request type",
            ),
        ),
        migrations.AlterField(
            model_name="helprequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "ACTIVE"),
                    ("IN PROCESSING", "IN PROCESSING"),
                    ("COMPLETED", "COMPLETED"),
                ],
                default="ACTIVE",
                verbose_name="Request status",
            ),
        ),
    ]
