# Generated by Django 4.2.5 on 2023-10-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_helprequest_request_type_alter_helprequest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helprequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("Functionality", "Functionality"),
                    ("Account", "Account"),
                    ("Pricing", "Pricing"),
                    ("Other", "Other"),
                ],
                default="Functionality",
                max_length=150,
                verbose_name="Request type",
            ),
        ),
        migrations.AlterField(
            model_name="helprequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "ACTIVE"),
                    ("IN PROCESSING", "IN PROCESSING"),
                    ("COMPLETED", "COMPLETED"),
                ],
                default="ACTIVE",
                max_length=150,
                verbose_name="Request status",
            ),
        ),
    ]
