# Generated by Django 4.2.5 on 2023-10-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0037_order_email_order_full_name_alter_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="with_user_creation",
            field=models.BooleanField(
                default=False, verbose_name="Create user for order"
            ),
        ),
    ]
